### ISSUE TITLE
[Meta] Issues related to nc-encrypt

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/nextcloudpi#1619]
**This is a meta issue to document issues related to nc-encrypt**

- [ ] encryption is terminated when php-fpm is restarted
- [ ] trusted domains are reset on decryption (templating issue?)
- [ ] btrfs backups don't work with nc-encrypt #1616 
- [ ] database is not encrypted by nc-encrypt
